version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: flask-db
    command:
      - --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: flask-api
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3306
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
